dataSourceClassName=com.mysql.cj.jdbc.MysqlDataSource
# El 3306 es el puerto por defecto, y password_manager es el nombre de la DB que creamos en MySQL
dataSource.url=jdbc:mysql://localhost:3306/password_manager?useSSL=false&serverTimezone=UTC

# Tu usuario de MySQL (casi siempre es root)
dataSource.user=root

# LA CONTRASEÑA A MYSQL WORKBENCH
dataSource.password=cloe2025

# Configuraciones optimizadas del Pool
dataSource.cachePrepStmts=true
dataSource.prepStmtCacheSize=250
dataSource.prepStmtCacheSqlLimit=2048